## Numpy
* Numerical Python or numeric python
* NumPy is a programming language that deals with multi-dimensional arrays and matrices.
* NumPy supports a large number of mathematical operations.

## Why use Numpy
* NumPy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library.
* especially for matrix multiplication and reshaping.
* On top of that, NumPy is fast. In fact, TensorFlow and Scikit.


## how to Install numpy
* Numpy is installed by default in anaconda

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.5


## Numpy arrays

In [3]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [5]:
data=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# Mathematical Operations
a1=np.array([3,5,7,9])
a2=np.array([2,4,6,8])
print(a1+a2)
print(a1-a2)

[ 5  9 13 17]
[1 1 1 1]


In [8]:
# Shape Of Array
data=np.array([[1,2,3,4],[5,6,7,8]])
data1=np.array([[1.0,2.2,3.3,4.4],[5.5,6.6,7.7,8.8]])
print(np.shape(data1))
print(data1.dtype)

(2, 4)
float64


In [11]:
#numpy Zeros and Ones
#numpy Zeros
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [10]:
#numpy Ones
np.ones((3,2),dtype=int)


array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
#numpy reshape
data2=np.array([[1,2,3,4],[6,7,8,9]])
print(data2)
data2.reshape((4,2))

[[1 2 3 4]
 [6 7 8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [33]:
#numpy Flatten
data2.flatten()

array([1, 2, 3, 4, 6, 7, 8, 9])

In [12]:
#numpy hstack(data apended horizontally)

np.hstack((a1,a2))

array([3, 5, 7, 9, 2, 4, 6, 8])

In [13]:
#numpy vstack(data apended vertically)
np.vstack((a1,a2))

array([[3, 5, 7, 9],
       [2, 4, 6, 8]])

In [16]:
# to caluculate mean 
data2.mean()

5.0

In [17]:
# To calculate standard deviation
data2.std()

2.7386127875258306

In [20]:
#Generate random numbers
d=np.random.randint(1,30,(3,3))

In [21]:
d

array([[11, 17, 29],
       [21, 21, 20],
       [28, 21, 12]])

In [22]:
#syntax---->np.random.normal(loc(mean),scale(std),size(no of elements))
np.random.normal(5,4,10)

array([ 6.13321103,  7.70933203, 10.30403954,  3.13773386,  3.56805509,
       10.51336155, 10.21875605,  2.47654614,  4.09548188,  6.10589908])

In [24]:
d

array([[11, 17, 29],
       [21, 21, 20],
       [28, 21, 12]])

In [25]:
#numpy statistical functions(min,max,mean,standard deviation)
d.min()

11

In [26]:
d.max()

29

In [47]:
d.mean()

16.333333333333332

In [48]:
d.std()

6.411794687223781

In [49]:
d.T

array([[25, 20, 14],
       [14, 22, 10],
       [ 3, 20, 19]])

In [51]:
d1=np.array([1,2,3,4])
np.array([d1,pow(d1,3)])

array([[ 1,  2,  3,  4],
       [ 1,  8, 27, 64]])

In [53]:
d

array([[25, 14,  3],
       [20, 22, 20],
       [14, 10, 19]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
a1.dot(a2)

140

In [62]:
a=np.array([1,2,3,4]*3)
print(a)
#np.diag(a)

[1 2 3 4 1 2 3 4 1 2 3 4]


In [63]:
#repeat
a=np.repeat([1,2,3,4],3)

In [64]:
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [65]:
#Arange function
#Syntax --->arange(start,stop,step)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [69]:
#numpy linspace(default=50)
#syntax -----> linspace(start,stop,num,endpoint)
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [71]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [72]:
# indexing slicing
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
x[0] #first row

array([1, 2, 3])

In [75]:
x[1] #second row

array([4, 5, 6])

In [76]:
x[:,1]

array([2, 5])

In [77]:
x[1,:2]

array([4, 5])

In [27]:
s=input().split('@')
print(s)


vidyachintala@gmail.com
['vidyachintala', 'gmail.com']
